- set_fact:
    backup_path: "{{ qtdsync_backups_path }}/{{ backup_user }}"
    config_path: "{{ qtdsync_rsyncd_config_folder }}/{{ backup_user }}.conf"

- name: "Create per user backup directory: '{{ backup_path }}'"
  become: yes
  file:
    path: "{{ backup_path }}"
    state: directory
    mode: 0755
    owner: "{{ backup_user }}"
    group: "users"

- name: "Create rsyncd config: '{{ config_path }}'"
  become: yes
  template:
    src: "rsyncd_user.conf"
    dest: "{{ config_path }}"
  notify: restart rsync daemon
