- name: Install ssh tools
  become: yes
  package: name={{ item }}
  with_items:
  - xorg
  - xauth
  - openssh-client
  - openssh-server

- name: Add authorized keys
  become: yes
  authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ ssh_pub_files }}"
