- name: Install btrfs tools
  become: yes
  package:
    name: btrfs-tools

- import_tasks: tasks/status-helper.yml

- include_tasks: tasks/volume.yml
  with_items: "{{ volumes }}"
  loop_control:
    loop_var: volume
