- name: Install btrfs tools
  become: yes
  package:
    name: btrfs-tools

- import_tasks: tasks/mkfs.yml
- import_tasks: tasks/mount.yml
- import_tasks: tasks/quota.yml
- import_tasks: tasks/subvolumes.yml
- import_tasks: tasks/status.yml
