- name: "Ensure subvolume: '{{ btrfs_subvolumes_path }}/{{ item }}' not already existing"
  become: yes
  command: "btrfs subvolume list {{ btrfs_subvolumes_path }}/{{ item }}"
  register: subvolume_list
  changed_when: false
  ignore_errors: true
  no_log: true

- name: "Create subvolume: '{{ btrfs_subvolumes_path }}/{{ item }}'"
  become: yes
  command: "btrfs subvolume create {{ btrfs_subvolumes_path }}/{{ item }}"
  when: subvolume_list.rc != 0

- name: "Ensure subvolume '{{ btrfs_subvolumes_path }}/{{ item }}' is accessible by 'users' group:"
  become: yes
  file:
    path: '{{ btrfs_subvolumes_path }}/{{ item }}'
    group: 'users'
    mode: '0775'
