- name: "Check if quotas enabled: '{{ volume.mount_path }}'"
  become: yes
  command: "btrfs qgroup show {{ volume.mount_path }}"
  register: qgroup_show
  changed_when: false
  failed_when: false
  ignore_errors: true
  no_log: true

- name: "Enable quota support on volume: '{{ volume.mount_path }}'"
  become: yes
  command: "btrfs quota enable {{ volume.mount_path }}"
  when: qgroup_show.rc != 0
