- name: "Install helper to show volume status: '{{ btrfs_status_helper_path }}'"
  become: yes
  template:
    src: "btrfs-status"
    dest: "{{ btrfs_status_helper_path }}"
    owner: "root"
    group: "root"
    mode: 0755

- set_fact:
    timer_tags:
      - key: "btrfs-status-{{ btrfs_pool_label }}"
        value:
          timer_command: "/bin/bash -c \"{{ btrfs_status_helper_path }} {{ btrfs_mount_path }} > {{ btrfs_status_log_file }}\""
          timer_user: root
          timer_persistent: yes
          timer_AccuracySec: 1m
          timer_OnCalendar: "*-*-* 03:00:00"

- include_role:
    name: ansible-systemd-timers
    apply:
      become: yes
  vars:
    timers:
      - "{{ timer_tags | items2dict }}"
