- name: "Ensure filesystem with label: '{{ btrfs_pool_label }}' not already existing"
  command: "blkid --label {{ btrfs_pool_label }}"
  register: blkid
  changed_when: false
  failed_when: false
  ignore_errors: true
  no_log: true

- name: "Create btrfs filesystem on devices: '{{ btrfs_dev_list|join(' ') }}'. Use 'wipefs -a <path>' to clean a not empty device."
  become: yes
  command: "mkfs.btrfs --metadata {{ 'raid1' if btrfs_raid1_metadata else 'raid0' }} --data {{ 'raid1' if btrfs_raid1_data else 'raid0' }} --label {{ btrfs_pool_label }} {{ btrfs_dev_list|join(' ') }}"
  when: blkid.rc != 0

- name: "Create mount point directory: '{{ btrfs_mount_path }}'"
  become: yes
  file:
    path: "{{ btrfs_mount_path }}"
    state: directory

- name: "Mount filesystem with label: '{{ btrfs_pool_label }}' at '{{ btrfs_mount_path }}'"
  become: yes
  mount:
    src: 'LABEL={{ btrfs_pool_label }}'
    path: '{{ btrfs_mount_path }}'
    fstype: btrfs
    state: mounted

- import_tasks: tasks/volume-status.yml

- import_tasks: tasks/quota.yml

- name: "Create subvolumes directory: '{{ btrfs_subvolumes_path }}'"
  become: yes
  file:
    path: "{{ btrfs_subvolumes_path }}"
    state: directory

- include_tasks: tasks/subvolume.yml
  with_items: "{{ btrfs_subvolume_list }}"
  loop_control:
    loop_var: subvolume
