#!/bin/bash

if [[ "$EUID" -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi


{% for device in disk_monitoring_devices %}
smartctl -t long {{ device.path }} -d {{ device.smart_type|default('auto') }}
{% endfor %}
