- hosts: all

  pre_tasks:
  - name: Update package manager repositories
    become: yes
    apt:
      update_cache: yes
    changed_when: False

  - import_tasks: tasks/ubuntu_apt.yml
  - import_tasks: tasks/basicsetup.yml
  - import_tasks: tasks/system_tools.yml
  - import_tasks: tasks/users.yml
    vars:
      # change passwords later with 'sudo passwd clang' etc.
      add_users:
        - 'clang'
        - 'kodi'

  roles:
  - role: swapfile
  - role: bash
  - role: tmux

  - role: git-tools
    vars:
      git_aliases: on
      git_rerere: on
      git_editor_nano: on
      git_prompt: on
      git_archivestotext: off
      git_docxtotext: off
      git_pdftotext: off
      git_xlsxtotext: off

  - role: btrfs
    vars:
      volumes:
        - label: "pool-main"
          mount_path: "/mnt/pool-main"
          mkfs_options: "--data raid1 --metadata raid1"
          status_log_path: "/mnt/pool-main/subvolumes/share-main"
          devices:
            - "/dev/sdc"
            - "/dev/sdd"
          subvolumes:
            - "share-main"

  # note: creation of filesystems on big disks may take a long time to finish
  - role: filesystem
    vars:
      filesystems:
        - label: "backups"
          device: "/dev/sde"
          mount_path: "/mnt/backups"
          type: "ext4"

  - role: ansible-role-hdparm
    become: yes
    vars:
      # see https://linux.die.net/man/8/hdparm for options
      # or default config file http://manpages.ubuntu.com/manpages/trusty/man5/hdparm.conf.5.html
      hdparm_devices:
        - dev: /dev/sdc
          options:
            - "spindown_time = 180" # -S: Count of 5 seconds or other if bigger then 240.
            - "apm = 64"            # -B: 1-127 allow spindown. Lower value means more power saved.
        - dev: /dev/sdd
          options:
            - "spindown_time = 180" # 15 minutes
            - "apm = 64"
        - dev: /dev/sde
          options:
            - "spindown_time = 180"
            - "apm = 64"

# Because the virtual disks do not support SMART this role is disabled. Enable on real hardware.
#  - role: disk-monitoring
#    vars:
#      disk_monitoring_status_log_path: "/mnt/pool-main/subvolumes/share-main"
#      disk_monitoring_devices:
#        - path: '/dev/sda'
#          smart_type: 'scsi'  # type used in the -d parameter of smartctl
#          temp_type: 'SATA'   # TYPE field used of hddtemp
#        - path: '/dev/sdb'
#          smart_type: 'scsi'
#        - path: '/dev/sdc'

  - role: ansible-role-samba
    become: yes
    vars:
      # change passwords later with 'sudo smbpasswd clang' etc.
      samba_users:
        - name: clang
          password: clang
        - name: kodi
          password: kodi
      samba_shares:
        - name: share-main
          path: "/mnt/pool-main/subvolumes/share-main"
          browseable: on
          group: users
          valid_users: +users
          write_list: clang
          include_file: "share-main-include.conf"
        # Only to show the backuped data. In real system this is not needed because of snapshots
        - name: share-main-backup
          path: "/mnt/backups/share-main"
          browseable: on
          group: users
          valid_users: +users

  - role: btrbk
    vars:
      btrbk_pool_label: "pool-main"
      btrbk_mount_path: "/mnt/pool-main"
      btrbk_subvolumes:
        - name: "share-main"
          snapshot_preserve_min: "1h"
          snapshot_preserve: "24h 14d 5w 3m"
          samba_config_file: "/etc/samba/share-main-include.conf"
          timer_OnCalendar: "*-*-* *:00,30:00"

  - role: rsync
    vars:
      rsync_tasks:
        - name: "backup-share-main"
          src: "/mnt/pool-main/subvolumes/share-main/"
          dest: "/mnt/backups/share-main/"
          timer_OnCalendar: "*-*-* *:05:00"

  - role: rsync-daemon
    vars:
      rsyncd_user: "qtdsync"
      rsyncd_password: "qtdsync"
      rsyncd_backups_path: "/mnt/pool-main/subvolumes/share-main/backups"
      rsyncd_backups:
        - user_name: 'clang'
          subfolders:
            - 'lang-ct2014'
            - 'lang-xps13'
        - user_name: 'kodi'
