- hosts: all

  pre_tasks:
  - name: Update package manager repositories
    become: yes
    apt:
      update_cache: yes
    changed_when: False

  - import_tasks: tasks/ubuntu_apt.yml
  - import_tasks: tasks/basicsetup.yml
  - import_tasks: tasks/system_tools.yml
  - import_tasks: tasks/users.yml
    vars:
      add_users:
        - 'clang'
        - 'kodi'
      # change passwords later with 'sudo passwd clang' etc.

  roles:
  - role: swapfile
  - role: bash
  - role: tmux

  - role: git-tools
    vars:
      git_aliases: on
      git_rerere: on
      git_editor_nano: on
      git_prompt: on
      git_archivestotext: off
      git_docxtotext: off
      git_pdftotext: off
      git_xlsxtotext: off

  - role: btrfs
    vars:
      btrfs_dev_list_string: "/dev/sdc /dev/sdd"
      btrfs_pool_label: "pool-main"
      btrfs_mount_path: "/mnt/pool-main"
      btrfs_raid1_data: on
      btrfs_raid1_metadata: on
      btrfs_status_log_path: "/mnt/pool-main/subvolumes/share-main"
      btrfs_subvolume_list:
        - "share-main"

  # note: creation of filesystems on big discs may take a long time to finish
  - role: filesystem
    vars:
      filesystems:
        - label: "backups"
          device: "/dev/sde"
          mount_path: "/mnt/backups"
          type: "ext4"

  # see https://github.com/bertvv/ansible-role-samba
  - role: ansible-role-samba
    become: yes
    vars:
      # change passwords later with 'sudo smbpasswd clang' etc.
      samba_users:
        - name: clang
          password: clang
        - name: kodi
          password: kodi

      samba_shares:
        - name: share-main
          path: "/mnt/pool-main/subvolumes/share-main"
          browseable: on
          group: users
          valid_users: +users
          write_list: clang
          include_file: "share-main-include.conf"
        # Only to show the backuped data. In real system this is not needed because of snapshots
        - name: share-main-backup
          path: "/mnt/backups/share-main"
          browseable: on
          group: users
          valid_users: +users

  - role: btrbk
    vars:
      btrbk_pool_label: "pool-main"
      btrbk_mount_path: "/mnt/pool-main"
      btrbk_subvolumes:
        - name: "share-main"
          snapshot_preserve_min: "1h"
          snapshot_preserve: "12h 14d 5w 3m"
          samba_config_file: "/etc/samba/share-main-include.conf"
          timer_OnCalendar: "*-*-* *:00,10,20,30,40,50:00"

  - role: rsync
    vars:
      rsync_tasks:
        - name: "backup-share-main"
          src: "/mnt/pool-main/subvolumes/share-main/"
          dest: "/mnt/backups/share-main/"
          timer_OnCalendar: "*-*-* *:05:00"

  - role: rsync-daemon
    vars:
      rsyncd_user: "qtdsync"
      rsyncd_password: "qtdsync"
      rsyncd_backups_path: "/mnt/pool-main/subvolumes/share-main/backups"
      rsyncd_backups:
        - user_name: 'clang'
          subfolders:
            - 'lang-ct2014'
            - 'lang-xps13'
        - user_name: 'kodi'
