- hosts: all

  pre_tasks:
  - name: Update package manager repositories
    become: yes
    apt:
      update_cache: yes
    changed_when: False

  - include_tasks: tasks/ubuntu_apt.yml
  - import_tasks: tasks/users.yml
    vars:
      add_users: ['clang', 'kodi']

  tasks:
  - include_tasks: tasks/basicsetup.yml
  - include_tasks: tasks/system_tools.yml
  - include_tasks: tasks/virtualbox_additions.yml
  - include_tasks: tasks/buildtools.yml

  roles:
  - role: ssh
    vars:
      ssh_pub_files: ['ssh_key_clang_home.opub']

  - role: swapfile
  - role: bash
  - role: tmux

  - role: git-tools
    vars:
      git_aliases: on
      git_rerere: on
      git_editor_nano: on
      git_prompt: on
      git_archivestotext: off
      git_docxtotext: off
      git_pdftotext: off
      git_xlsxtotext: off

  - role: dockerce

  - role: btrfs
    vars:
      btrfs_dev_list_string: "/dev/sdc /dev/sdd"
      btrfs_pool_label: "pool-main"
      btrfs_mount_path: "/mnt/pool-main"
      btrfs_raid1_data: on
      btrfs_raid1_metadata: on
      btrfs_subvolume_list:
        - "share-main"
        - "test"

  # see sambagithub.com/bertvv/ansible-role-samba for more info about this role
  - role: ansible-role-samba
    become: yes
    vars:
      # change passwords later with 'sudo smbpasswd clang' etc.
      samba_users:
        - name: clang
          password: clang
        - name: kodi
          password: kodi

      samba_shares:
        - name: share-main
          path: "/mnt/pool-main/subvolumes/share-main"
          browseable: on
          group: users
          write_list: clang
          valid_users: +users
          include_file: "share-main-include.conf"

  - role: btrbk
    vars:
      btrfs_pool_label: "pool-main"
      btrfs_mount_path: "/mnt/pool-main"
      btrbk_subvolumes:
        - name: "share-main"
          snapshot_preserve_min: "2h"
          snapshot_preserve: "12h 14d 5w 3m"
          samba_config_file: "/etc/samba/share-main-include.conf"
        - name: "test"
          snapshot_preserve: "1d"
