---

- name: Add Docker CE GPG key
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker CE APT repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install Docker CE and dependencies
  become: yes
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
    state: present
    update_cache: yes

- name: Create group docker
  become: yes
  group:
    name: docker

- name: Add docker user to docker group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    append: yes
    groups: docker
