- name: Install btrbk
  become: yes
  package:
    name: btrbk

- name: "Create snapshots directory: '{{ btrbk_snapshots_path }}'"
  become: yes
  file:
    path: "{{ btrbk_snapshots_path }}"
    state: directory

- include_tasks: tasks/config.yml
  with_items: "{{ btrbk_subvolumes }}"

- include_tasks: tasks/samba_config.yml
  with_items: "{{ btrbk_subvolumes }}"
