# we have to create a dict out of a list to be able to use a variable as key
# see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#items2dict-filter
- set_fact:
    timer_tags:
      - key: "btrbk-{{ btrbk_pool_label }}-{{ subvolume.name }}"
        value:
          timer_command: "/usr/sbin/btrbk -c {{ btrbk_config_path }}/{{ subvolume.name }}.conf run"
          timer_user: root
          timer_persistent: yes
          timer_AccuracySec: 1m
          timer_OnCalendar: "{{ subvolume.timer_OnCalendar | default('*-*-* 03:00:00') }}"
# see: https://www.freedesktop.org/software/systemd/man/systemd.timer.html
# for definition of value in timer_OnCalendar

# see: https://github.com/vlcty/ansible-systemd-timers
- include_role:
    name: ansible-systemd-timers
    apply:
      become: yes
  vars:
    timers:
      - "{{ timer_tags | items2dict }}"
